---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Install requirement for ansible - python-apt
      apt:
        name: python-apt
        update_cache: yes
    - name: Add key for custom repository
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
        state: present
    - name: Add custom repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongo-org-3.2.list
    - name: Install MongoDB apt
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
    - name: Autostart mongod daemon
      service:
        name: mongod
        enabled: yes

