---
# tasks file for app
- name: Show info about the environments this host belong to
  debug:
    msg: "This host is in {{ env }} environment!"
- name: print db_host
  debug:
    msg: "db_host is {{ db_host }}" #variable from dynamic inventory from terraform-inventory
    #correct for normal inventory file    msg: "{{hostvars['dbserver']['ansible_default_ipv4']['address']}}"

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma
- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser
- name: enable puma
  systemd: name=puma enabled=yes

