---
# tasks file for app
- name: Show info about the environments this host belong to
  debug:
    msg: "This host is in {{ env }} environment!"
- name: print db_host
  debug:
    msg: "db_host is {{ db_host }}" #variable from dynamic inventory from terraform-inventory
    #correct for normal inventory file    msg: "{{hostvars['dbserver']['ansible_default_ipv4']['address']}}"

- include: ruby.yml
- include: puma.yml
